language: node_js
node_js:
- 10
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: relife_abyss@qq.com
  api_key:
    secure: O7PXGtwOr2GHaWRPzpdnOTpQ5edWYOcWQfUHpHKzA036cooc2YSaJMTWNHEb6acM8mmrgPZkQlRYqmDA7yVPrA7VKR+BsNKebvg0catAKDQ3OA7DA05QsuNEz0OkVbexWlcQsLIehIyJOQlP6d2OaBtMp9txWuNJvusGGjg3gwnx6fEs8RSwRUsMiBfeL09shZKs/osY9f5TwW/XSVlDcPP+7iYx0+IzZ1mAhKJGC4qDQMH7JRYljnSGXdhotY/VP5Y6wefJ+roNMSfT8kB6F29g5jdRI2t76F/suCl5vCHe83vTeQb/yUoIShMuK1i9Rw8kYMjeohye82NWUZbzZgE7KeEWJhOM+p5lK5HPEeXnOvUlj2nEzHqMEfqiHI6g0EXeRjltgylF5X29hbt0c+I3Ao+hU1oF9wZYd6mCvB+PJHiU3y+AIFfGFrVDmbtQ7Dp8JmWpzTFzJ2XPudBysHdmYqACb33eE5biKiJ/5kTpbyZ6Vq4x9uUduvsYktCGRQe9aC5jBdayd0ZPaiCT5ZUJ0ZoVfs7ddcD+2rQwRkn10rl/X/266JPQjpU71aUyeUJ45ZRnXcZjfRz3OY8rTLdDoZgxbOAAesZZLWc5BscpnbTPocTgVOQ4tJGUXuBEEQgd9x/89EdS6oyim5fiEkKsCid5Rmf6sJeqgWOMjms=
  on:
    tags: true
    repo: MXXXXXS/classify-my-files
