language: node_js
node_js:
- 10
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: relife_abyss@qq.com
  api_key:
    secure: fgy5el49umt4YEPf9EPBe+NSPukzYqOPY2YWpFfIi+iYm5+D/MLPkoAeb5+CB4fUyTCrlUgstPRL7SB7vi0q2RcEjXWoWjX/mmgMnSnrr3x4+aV4Qr9cFZK9RAbwuBsmosvGEgRVGhauKXsiwMLS17f2NfWAap1Pp4wk0wQJAapFLL/jInJ/kPf3ABeFdjqzZLby5H3pT9fVs6i1qCCjdXcCyl6ErRZVDFhpLxWKs3NQefepjlxJY13+CVHWAE2JPiHacvz81H6kx0BoH6psdPwNIm+x61aKmYz/2KLgxFmNfAGtQcCgGHQWY+mEKymBSgcOJtzAsm5pt0mYVDMlroJAswCQpGkJW+UbN+/5HrGtKkfewPVSIXbKTjx1vqdttCe7jXk6A2s0FGhliZijXfepY4JLxqCRQefvufB5KcCL9BQbrx7ciWqLBEzdNgCQA+VsviTCGMDOvoxHujZm3MuYwrvM6WSdOSIQcW3RBr7Wp9sl8DUtfthHaGx/ih7IPvA1kzJZmJc1mOroLqUP0Q0S4+YEqVkIGC/v49MqDVZe3ISgTn1r3FItssZKNUTEpvMaOXm6ph/SySBg1ek3sDmxLJuoJakIMWY9BoB9b2GBe4gbTA/V+rgMINom6WSqlN4di+uckVAEvnECR4NNEdMBhN3mIpgUMt3Ycuhawe8=
  on:
    tags: true
    repo: MXXXXXS/classify-my-files
