const exiftool = require('node-exiftool')
const exiftoolBin = require('dist-exiftool')
const ep = new exiftool.ExiftoolProcess(exiftoolBin)
ep
    .open()
    .then(() => ep.readMetadata('C:/Users/Tamako/Pictures/pixiv/bkgd_mashiro.jpg', ['-File:all']))
    .then(console.log, console.error)
    .then(() => ep.close())
    .then(() => console.log('closed exifool'))
    .catch(console.error)